config/routes.rb
Gezwitscher::Application.routes.draw do

  devise_for :users
 
  match '/:id' => 'users#show', :constraints => {:id => /\d+/ }
  resources :users do
    resources :messages
    resources :subscriptions
  end

  root :to => "welcome#index"
  match 'intro' => 'welcome#intro'

end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_length_of :text,	:maximum => 142
  belongs_to :user
end

app/models/message_observer.rb
class MessageObserver < ActiveRecord::Observer
  def after_create(message) 
    Subscription.where(:author_id=>message.user_id).each{|subscription|
      rel=MessageRelation.new
      rel.user_id=subscription.user_id
      rel.message_id=message.id
      rel.save
    }

    User.find_by_sql(["select users.* from users,messages where text like '%'||email||'%' and messages.id=?",message.id]).each{|user|
      rel=MessageRelation.new
      rel.user_id=user.id
      rel.message_id=message.id
      rel.save
    }

  end
end

app/models/message_relation.rb
class MessageRelation < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates_uniqueness_of :user_id, :author_id

  belongs_to :user
  def author
    User.find(self.author_id)
  end
  def author=(a)
    if a
      author_id=a.id
    else
      author_id=nil
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :messages
  has_many :subscriptions
  def am_i_subscribed?(current_user)
    my_subscription(current_user)
  end
  def my_subscription(current_user)
    Subscription.where(:user_id=>current_user.id,:author_id=>self.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
require 'pp'


class MessagesController < ApplicationController
  before_filter :authenticate_user!

  before_filter :get_user


  READONLY=true

  # GET /messages
  # GET /messages.xml
  def index
    @messages = @user.messages.order("created_at desc").limit(30)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # POST /messages.xml
  def create
    @message = Message.new(params[:message])
    @message.user_id=current_user.id # always save as current_user - never as selected
    respond_to do |format|
      if @message.save
        MessageRelation.create(:user_id=>current_user.id,:message_id=>@message.id)
        format.html { redirect_to([@message.user], :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  if false

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end




  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
  end


  private
  def get_user
    @user=User.where(:id=>params[:user_id]).first
    @subscribed=Subscription.where(:author_id=>@user.id, :user_id=>current_user.id).first
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    user=User.where(:id=>params[:user_id]).first
    if user and user!=current_user
      s=Subscription.new
      s.author_id=user.id
      s.user_id=current_user.id
      s.save
    end  
    redirect_to user_path(user)
  end
  def destroy
    s=Subscription.where(:id=>params[:id],:user_id=>current_user.id).first
    if s
      other_user_id=s.author_id
      s.delete
      redirect_to user_path(User.find(other_user_id))
    else
      redirect_to '/'
    end
  end
end

app/controllers/users_controller.rb
require 'pp'

class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user=User.where(:id=>params[:id]).first
    if @user
      redirect_to user_messages_path([@user])
    else
      redirect_to '/' unless @user
    end
  end
  def index
    @users=User.limit(10)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      @subscriptions=Subscription.where(:user_id=>current_user.id).all
      @messages=MessageRelation.where(:user_id=>current_user.id).order("created_at desc").limit(30).map{|relation|relation.message}
      @followers=Subscription.where(:author_id=>current_user.id).all
      @someusers=User.limit(10)
      render :mixed_list
    else
      render :index
    end
  end
  def intro
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gezwitscher</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id='user_info'>
  <%if current_user%>
    <%= current_user.email %>
    <%= link_to 'logout', '/users/sign_out'%>
  <%end%>
</div>
<div id='title'>
  <a href='/'>gZwitscher</a>
</div>
<%= yield %>
<div id='footer'>
  Impressum
  Kontakt
  Sonstiges
</div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for([current_user,@message]) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text, :size=>142 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message_list.html.erb
<% #= link_to 'New Message', new_user_message_path(current_user) %>

<%= render('messages/new') %>

<br />
<div class='messages'>
  <% @messages.each do |message| %>
    <div class='entry'>
      <div class='head'>
        <%= time_ago_in_words(message.created_at) %> ago
        <%= link_to message.user.email, [message.user] %>
        wrote:
      </div>
      <div class='message'>
        '<%=h message.text %>'
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_new.html.erb
<%= form_for([current_user,@message||Message.new]) do |f| %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text, :size=>142 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages of <%=@user.email%> </h1>
<% unless @user==current_user %>
  <% unless @subscribed %>
    <%= button_to 'Subscribe', user_subscriptions_path(@user), :method => :post %>
  <% else %>
    <%= button_to 'Unsubscribe', user_subscription_path(@user,@subscribed), :method => :delete %>
  <% end %>
<% end %>

<%= render :partial=>'message_list' %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', user_messages_path(current_user) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%=h @message.text %>
</p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>


<%= link_to 'Edit', edit_user_message_path(@message.user_id,@message) %> |
<%= link_to 'Back', user_messages_path(@message.user_id) %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email,[user] %>
      <% if user!=current_user %>
        <% if user.am_i_subscribed?(current_user) %>
          <%= button_to "Unsubscribe", user_subscription_path(current_user,user.my_subscription(current_user)),:method=>:delete %>
        <% else %>
          <%= button_to "Subscribe", user_subscriptions_path(user),:method=>:post %>
        <% end %>
      <% end %>
    </li>
<% end %>
</ul>

app/views/welcome/_subscriptions.html.erb
<h2>My subscriptions</h2>

<table>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= link_to subscription.author.email,[subscription.author] %></td>
    <td><%= button_to 'Remove', [subscription.user,subscription], :confirm => "Really ?", :method=>:delete%></td>
  </tr>
<% end %>
</table>

<h2>My followers</h2>
<table>

<% @followers.each do |follower| %>
  <tr>
    <td><%= link_to follower.author.email,[follower.author] %></td>
  </tr>
<% end %>
</table>

app/views/welcome/index.haml
#welcome
 Welcome to Gezwitscher
#destiny
 =link_to "Introduction",:action=>:intro
 %a{:href=>'/users/sign_in'} Login
 %a{:href=>'/users/sign_up'} Register now

app/views/welcome/intro.html.haml
Some introduction to this app.

app/views/welcome/mixed_list.html.erb
<h1>All messages</h1>

<div id='someusers'>
  Some users:
  <ul>
   <% @someusers.each{|user| %>
     <li><%= link_to user.email,[user] %></li>
   <% } %>
  </ul>
  <%= link_to "more...",users_path %>
</div>

<%= render 'messages/message_list' %>

<%= render(:partial=>'subscriptions') %>